# Generated by Django 4.0.3 on 2022-04-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHospital', '0002_remove_sucursales_cantidaddepersonal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
            ],
        ),
    ]
